### ISSUE TITLE
First time synchronisation cannot find device ID

### ISSUE THREAD

**Issue by jjmark15** [oxtyped/gpodder2go#25] opened 2024-04-14 12:19 UTC
I am running gpodder2go from Docker with the AntennaPod client. I am experiencing an issue where whenever I try to synchronise, the server errors with the following:

```
gpodder2go-gpodder2go-1  | 2024/04/14 12:12:34 unable to find device id from device name: &errors.errorString{s:"sql: no rows in result set"}
gpodder2go-gpodder2go-1  | 2024/04/14 12:12:34 error retrieving subscription history: &errors.errorString{s:"sql: no rows in result set"}
```

I have created a user and have successfully authenticated with the AntennaPod client.

**Comment by stillbeben** [comment] 2024-04-14 20:17
Same here after performing an update from versio 0.1.2 to 0.2.0. I've removed the database and created a new one by running:
```
$ VERIFIER_SECRET_KEY=xxx ./gpodder2go init
$ VERIFIER_SECRET_KEY=xxx ./gpodder2go accounts create myuser --email="no-reply@example.org" --name="myuser" --password='mysupersecretpassword'
```

After starting via systemd I've logged in via AntennaPod:
```
Apr 14 20:07:06 n-fi bash[1749633]: 2024/04/14 20:07:06 💻 Starting server at localhost:3005
Apr 14 20:07:20 n-fi bash[1749633]: 2024/04/14 20:07:20 [n-fi/NefQ4sXOVY-000001] "POST http://gpodder2go.example.org/api/2/auth/myuser/login.json HTTP/1.1" from ::1 - 200 0B in 1.058351ms
Apr 14 20:07:20 n-fi bash[1749633]: 2024/04/14 20:07:20 [n-fi/NefQ4sXOVY-000002] "GET http://gpodder2go.example.org/api/2/devices/myuser.json HTTP/1.1" from ::1 - 200 2B in 356.397µs
Apr 14 20:07:21 n-fi bash[1749633]: 2024/04/14 20:07:21 username is myuser, deviceName is antennapod_on_pixel_7
Apr 14 20:07:21 n-fi bash[1749633]: 2024/04/14 20:07:21 DDR is &apis.DeviceDataRequest{Caption:"AntennaPod on Pixel 7", Type:"mobile"} and "myuser" "antennapod_on_pixel_7"
Apr 14 20:07:21 n-fi bash[1749633]: 2024/04/14 20:07:21 [n-fi/NefQ4sXOVY-000003] "POST http://gpodder2go.example.org/api/2/devices/myuser/antennapod_on_pixel_7.json HTTP/1.1" from ::1 - 200 0B in 3.606609ms
Apr 14 20:07:42 n-fi bash[1749633]: 2024/04/14 20:07:42 [n-fi/NefQ4sXOVY-000004] "POST http://gpodder2go.example.org/api/2/auth/myuser/login.json HTTP/1.1" from ::1 - 200 0B in 304.698µs
Apr 14 20:07:42 n-fi bash[1749633]: 2024/04/14 20:07:42 [n-fi/NefQ4sXOVY-000005] "GET http://gpodder2go.example.org/api/2/subscriptions/myuser/antennapod_on_pixel_7.json?since=0 HTTP/1.1" from ::1 - 200 45B in 724.145µs
Apr 14 20:07:42 n-fi bash[1749633]: 2024/04/14 20:07:42 error getting device_sync_group_id: &errors.errorString{s:"sql: no rows in result set"}
Apr 14 20:07:42 n-fi bash[1749633]: 2024/04/14 20:07:42 error trying to retrieve devices in sync_group: sql: no rows in result set
Apr 14 20:07:42 n-fi bash[1749633]: 2024/04/14 20:07:42 [n-fi/NefQ4sXOVY-000006] "POST http://gpodder2go.example.org/api/2/subscriptions/myuser/antennapod_on_pixel_7.json HTTP/1.1" from ::1 - 500 0B in 491.784µs
```

**Comment by oxtyped** [comment] 2024-04-15 01:27
Thanks for the reports and logs! 🙇 

I think I might know the cause of the error. Will be pushing out a fix soon!

**Comment by oxtyped** [comment] 2024-04-16 08:02
Thanks again @jjmark15 and @stillbeben!

I've pushed out https://github.com/oxtyped/gpodder2go/commit/941e783d8060aa1c7e0220617483d9f2cbdf34f9 which fixes the issue with syncing when device does not have a sync group.

@jjmark15 I am unable to replicate your issue on antennapod. I'm not sure if this fix would have fixed your issue on your end, if you could, can you try pulling from main.

If it still does not solve it can you send me the entire output of your setup from `gpodder2go init` to `serve`? Thanks! 🙇

**Comment by jjmark15** [comment] 2024-04-16 16:07
@oxtyped the changes do resolve my issue! Thank you!.

P.S. Since I am not a maintainer I will assume you would wish to close this issue yourself.

**Comment by oxtyped** [comment] 2024-04-17 04:20
That's great to hear! ❤️ 

Closing this issue.

**Closed as completed by oxtyped** 2024-04-17 04:20 UTC
